# Generated by Django 3.0.2 on 2022-06-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=20)),
                ('item_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('tax_free_amount', models.FloatField()),
                ('shopped_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
