# Generated by Django 3.0.2 on 2022-06-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='tax_free_amount',
            field=models.IntegerField(),
        ),
    ]
